### ISSUE TITLE
Messy plot

### ISSUE THREAD

**Issue by Habbie** [armish/evsrc#4]
When feeding evsrc the whole history of https://github.com/PowerDNS/pdns (which does not take as long as I expected, so my compliments for that!) the correlations seem to make sense, but the first output plot is unreadable.

Picture: ![screenshot of 2 PDFs side by side](http://7bits.nl/tmp/fileshuttle/Screen%20Shot%202014-12-16%20at%2010.03.32%20-lESV4Befeq.png)

The two generated .sif files are at https://gist.github.com/anonymous/c2556ee83a90cf0861b3

The correlation in the left picture (0.3.pdf) is very accurate, those files go together.

I have no specific suggestion or request, other than "please give me a plot I can read". I hope you have some ideas!

**Comment by Habbie** [comment]
@pnavarrc only clicked your link just now, that's pretty awesome!

**Comment by pnavarrc** [comment]
Thanks! I think is still pretty limited, and it is for a software package that doesn’t seem to be too coupled. What would be the next steps in this research? This is really interesting.

**Comment by armish** [comment]
Yeah, this is really great Pablo -- it will be great when we couple your visualization with a better automated analysis option. I was originally planning to wrap this up as a web service so people can simply get on the website and investigate a GitHub repo, but that requires some resource management and web server development. We can facilitate this by making this whole system act like Travis, but again we would either need time or more hands to accomplish that goal.

The following two-three months will be pretty busy for me, so I might not be able to work/build on this as much as I would like to do :(

**Comment by cmdcolin** [comment]
I started doing a similar thing as @pnavarrc with cytoscape JS http://cmdcolin.github.io/evsrc-cytoscape/

Doesn't have all the cool features that the other one has, but perhaps could be extended!

**Comment by armish** [comment]
@cmdcolin: looks awesome! Thanks for doing this. If you would like me to add a link to you repository, feel free to send a PR my way.

**Comment by cmdcolin** [comment]
Awesome, will do :)
